---
# Source: https://github.com/jmuelbert/checkconnect/blob/main/workflow-templates/assets/mkdocs/mkdocs.yml
# See: https://www.mkdocs.org/user-guide/configuration/

# Project Information
site_name: checkconnect
site_url: https://io.github.org/jmuelbert/checkconnect/
site_description: >-
  A tester for differt hosts for available.

# Repository
repo_name: jmuelbert/checkconnect
repo_url: https://github.com/jmuelbert/checkconnect/
edit_uri: 'blob/main/docs/'

# Copyright
copyright: Copyright &copy; 2023 - 2024 J端rgen M端lbert

# Configuration
docs_dir: docs
site_dir: site

theme:
  name: material
  custom_dir: docs/.overrides

  # Static files
  static_templates:
    - 404.html

  # Default values, taken from mkdocs_theme.yml
  language: en
  direction: ltr
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    - navigation.path # Not compatible with navigation.expand
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  extra_css:
    - css/custom.css
  icon:
    repo: fontawesome/brands/github-alt
    logo: material/check-network-outline

# Page tree
nav:
  - Introduction: 'index.md'
  - QuickStart: 'quickstart.md'
  - Philosophy: 'philosophy.md'
  - Upgrade: 'upgrade.md'
  # - Advanced:
  - Guides:
      - Command Line: 'guides/commandline.md'
      - Configuration: 'guides/configuration.md'
      - Installation: 'guides/install.md'
      - Logging: 'guides/logging.md'
      - Troubleshooting: 'guides/troubleshooting.md'
  - Develop:
      - Environment Variables: 'developer/environment_variables.md'
      - Changelog: 'developer/changelog.md'
      - Release Notes: 'developer/release-notes.md'
      - API: 'developer/overview.md'
      - CLI: 'developer/cli.md'
      - Core: 'developer/core.md'
      - Configuration: 'developer/configuration.md'
  - Community:
      - faq: 'community/faq.md'
      - Contributing: 'community/contributing.md'
      - Code of Conduct: 'community/code_of_conduct.md'
      - Third Party Packages: 'community/third_party_packages.md'
  - About:
      - Authors: 'about/authors.md'
      - License: 'about/EUPL-1.2.md'

# Plugins
plugins:
  i18n:
    docs_structure: suffix
    languages:
      - locale: en
        default: true
        name: English
        build: true
      - locale: de
        name: Deutsch
        build: true
      - locale: it
        name: Italiano
        build: false
      - locale: es
        name: Espa単ol
        build: false

  # Enable for bug reports
  # info: {}
  # Built-in
  search:
    separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  autorefs: {}
  codeinclude: {}
  # Extra
  glightbox: {}
  minify:
    minify_html: true
  git-authors: {}
  git-revision-date-localized:
    type: date
    strict: false
    fallback_to_build_date: true
  table-reader: {}
  mike:
    alias_type: copy
  material/social: {}
  material/tags: {}
  mkdocstrings:
    enable_inventory: true
    default_handler: python
    handlers:
      python:
        paths: [src]
        options:
          show_root_heading: true
          show_object_full_path: false
          show_category_heading: false
          show_bases: true
          show_submodules: false
          show_if_no_docstring: false
          show_signature: false
          heading_level: 1
          filters: ['!^_']
  render_swagger: {}
  redirects:
    redirect_maps:
      conventions.md: philosophy.md
      upgrading.md: upgrade.md

# Markdown Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      # reduced to keep TOC nice under Changelog page
      toc_depth: 2
      permalink: true
  - tables
  - codehilite:
      css_class: highlight
  # Standard mkdocs Extensions
  - mkdocs-click
  - mkautodoc

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: jmuelbert
      repo: checkconnect
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - docs/.snippets
      auto_append:
        - links.txt
        - abbrs.txt
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true

# Customization
extra:
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Deutsch
      link: /de/
      lang: de
    - name: Italiano
      link: /it/
      lang: it
    - name: Espa単ol
      link: /es/
      lang: es
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jmuelbert
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/jmuelbert/checkconnect
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/jmuelbert/checkconnect/
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/checkconnect/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jmuelbert

watch:
  - mkdocs.yml
  - src/
  - docs/
